### ISSUE TITLE
Concept Screening - Materials

### ISSUE THREAD

**Issue by igorro** [igorro/FOWT-docs#24]

**Comment by patrickmcadam** [comment]
16/05/2024 @miladelgado @eleonorelaw 

Comments
- Concrete section looks good, appreciate the inclusion of the emerging technologies.
- Steel section looks good - any disadvantages considered?
- Hybrid section looks good.
- References are excellent.
- Presentation is excellent - although we will need to ensure it is consistent with other sections when compiled.
- Good idea to improve on site specific considerations. 

Action
- [ ] Are tables the best way to present this information?
- [ ] Could you create an introductory paragraph at the start to give a general overview, will improve the flow of the report. We can either do this when we compile the report or beforehand - just something to think about.

**Comment by miladelgado** [comment]
To be done:

- @eleonorelaw add steel disadvantages
- @miladelgado think about site specific considerations: maybe depending on the temperature of the water and the type o loading a specific material is better than the other
- @miladelgado write introductory paragraph for the section: mainly explaining the aim of the section, how it compares the use of steel and concrete in the specific site, regardless of the floating foundation type used.

@patrickmcadam I think tables are good for now as they make  a clear distinction between advantages/disadvatages. Also they give a lot of info in a smaller space. But I don't mind changing. We can also write more about more specific stuff in paragraphs.
