### ISSUE TITLE
Concept Screening - Mooring

### ISSUE THREAD

**Issue by igorro** [igorro/FOWT-docs#25]

**Comment by ash-thanga** [comment]
Me and Akshaye are focusing on Tension-Leg Platforms (TLP), especially technical characteristics, installation, deployment and performance.

**Comment by katrinachengg** [comment]
I worked on types of Mooring line, specifically chain, wire rope and synthetic fiber rope. Moving forward, I will look at chain catenary and other types of catenaries.

**Comment by miladelgado** [comment]
Tomorrow I will work on the TLP tendon. Materials, stresses... I might need to see how you have been structuring this to keep it consistent.

**Comment by miladelgado** [comment]
Catenary Mooring Type:

- Feasibility of all mooring lines with given water depth. @eleonorelaw 
- Connectors: explain what, why. Do we need them and if so which one is better? @katrinachengg 
- Anchorage: based on holding capacity. Consider discussing our type of soil and what anchorage is more suitable. @katrinachengg 
- Calculate the costs (comparison between the types of mooring and the anchors) TBD
- Decommissioning and maintenance of all options TBD
- Sustainability of all options TBD

**Comment by patrickmcadam** [comment]
16/05/2024

Comments on Catenary @ingridfung 
- Catenary mooring system: good. Ensure references are formalised when we compile report.
- Mooring line: good.
- Connectors: good
- [ ] Anchorage: good @miladelgado, what's the plan for the section that is copied from manual? Reference it or paraphrase?
- [ ] Cost: just include an intro paragraph for the tables and explain them.
- Environmental consideration: to be finished.

**Comment by patrickmcadam** [comment]
16/05/2024

Comments on Semi-taut @KennethChanCM 
- [ ] I'm guessing this section has just been started/incomplete. No worries.

**Comment by ash-thanga** [comment]
Im working on the environmental impacts and sustainability aspects of the various mooring systems.

**Comment by KennethChanCM** [comment]
The semi-taut mooring part has been completed, but the information is mainly on the scenarios when semi-taut configurations are used and there aren't a lot of qualitative analysis on the effectiveness of the configrations.

**Comment by miladelgado** [comment]
@patrickmcadam I think Katrina needed that info (what I copied and pasted into the report) to write some of her stuff.
@katrinachengg did you finish using it? can that be deleted?
