### ISSUE TITLE
Concept Screening - Anchor Systems

### ISSUE THREAD

**Issue by igorro** [igorro/FOWT-docs#26]

**Comment by Nyrvam** [comment]
Tuesday 15/05 Summary:
- Found 6 different types of anchoring with general strengths, installation method, site requirements.
- Possible from these information to qualitatively extrapolate but still lack of literature and quantitative results

Next Steps:

In depth literature review on each anchor type

- Equation for calculating
- Integration with mooring and floater type
- Deployability, Installation time and cost (look at precedent cases)
- Environmental impact

**Comment by igorro** [comment]
**Focus**
- Igor: piles, torpedo, and suction caissons
- Marvyn: anchors, vertical anchors, and dead weight
